[package]
name = "good_git"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
clap = { version = "4.5.4", features = ["derive"] }
hex = "0.4.3"
sha1 = "0.10.6"

[dev-dependencies]
tempfile = "3.10.1"
