on:
  pull_request:
  workflow_dispatch:
name: ci

permissions:
  contents: read

jobs:
  # Formatting for .yaml, .md, and other not-Rust things.
  prettier:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - run: npm install --global prettier@3.2.5
      - run: npx prettier --ignore-path .gitignore --write .
      - run: git diff --exit-code

  cargo-fmt:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - run: cargo --version
      - run: cargo fmt -- --check

  cargo-clippy:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - run: cargo --version
      - run: cargo clippy --all-targets --all-features -- -D warnings

  cargo-test:
    name: cargo-test-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-14]

    steps:
      - uses: actions/checkout@v4
      - run: cargo --version
      - run: cargo test --all-targets --all-features

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
