on:
  pull_request:
  workflow_dispatch:
name: ci

permissions:
  contents: read

jobs:
  cargo-fmt:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - run: cargo --version
      - run: cargo fmt -- --check

  cargo-clippy:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - run: cargo --version
      - run: cargo clippy --all-targets --all-features -- -D warnings

  cargo-test:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - run: cargo --version
      - run: cargo test --all-targets --all-features

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
